name: "container-image-build"
# on: [pull_request]

jobs:
  container-image-build:
    name: "Container Image Build"
    runs-on: ubuntu-latest
    env:
      REPO: "docker.io/kazuhikotsuji/my-app" # Set the name of the repository to use for the image

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Check out repository
        uses: actions/checkout@v2

      # It's possible to skip this step if this job is scheduled after an image-build job.
      # If that's the case, also set "Run wiz CLI docker image scan" step accordingly
      - name: Build the Docker image
        run: |
          IMAGE="$REPO:$(date +%s)"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build . --tag "$IMAGE" # Configure to fit the params you use to build your image

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push $IMAGE
